#!/bin/sh
#### dotfiles
if ! dir_exists "$HOME/.dotfiles-git-config"; then
    $sh_c "git clone --bare https://gitlab.com/ale-j/dotfiles.git $HOME/.dotfiles-git-config"
    #$sh_c "git clone --bare git@gitlab.com:ale-j/dotfiles.git $HOME/.dotfiles-git-config"
    $sh_c "/usr/bin/git --git-dir=$HOME/.dotfiles-git-config/ --work-tree=$HOME checkout --force"
    $sh_c "/usr/bin/git --git-dir=$HOME/.dotfiles-git-config/ --work-tree=$HOME config --local status.showUntrackedFiles no"
fi
