#!/bin/sh
# Open jdk 20.0.1
# https://jdk.java.net/20/
$sush_c "mkdir -p /opt/jdk"
wget https://download.java.net/java/GA/jdk20.0.1/b4887098932d415489976708ad6d1a4b/9/GPL/openjdk-20.0.1_linux-x64_bin.tar.gz -O ${PKG_DIR}jdk-20.tar.gz
$sush_c "tar xvf ${PKG_DIR}jdk-20*.tar.gz --directory /opt/jdk/"

# TODO:
# 2. install java language server
# 3. What esle do I need to run build and run the test in Expero project
# 4. install Scala
