#!/bin/sh
#### neo vim 'plugupdate'
$sh_c "curl -fLo ${XDG_DATA_HOME:-$HOME/.local/share}/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
$sh_c "nvim +PlugInstall +qa"
