#!/bin/sh
#### Xmonad v16.99 & xmobar v0.19 ?
# xmonad has a dependcy with dotfiles. it requiores xmonad.hs  you could create a dummy xmonad.sh
XMONAD_DIR="$HOME/.xmonad/"
#$sush_c "apt -y install haskell-platform"

# sources are needed for xmonad version newer than 0.15
if ! dir_exists "$XMONAD_DIR/xmonad"; then
    $sh_c "git clone https://github.com/xmonad/xmonad $XMONAD_DIR/xmonad"
    $sh_c "git clone https://github.com/xmonad/xmonad-contrib $XMONAD_DIR/xmonad-contrib"
    #$sh_c "git -C $XMONAD_DIR/xmonad checkout 33a86c0cdb9aa481e23cc5527a997adef5e32d42"
    #$sh_c "git -C $XMONAD_DIR/xmonad-contrib checkout 0c6fdf4e75dd4d31bc8423010fbabbab7c23ee03"
else
    # pulls latest. consider anchoring to the commmits above
    $sh_c "git -C ${XMONAD_DIR}xmonad pull"
    $sh_c "git -C ${XMONAD_DIR}xmonad-contrib pull"
fi

$sush_c "apt -y install haskell-stack"
$sh_c "stack upgrade"

# installing  xmonad from source using stacks yields a newer version 16.999
if ! file_exists "$HOME/.local/bin/xmonad"; then
    $sush_c "apt -y install libx11-dev libxft-dev libxinerama-dev libxrandr-dev libxss-dev libxss-dev"
    $sh_c "cd $XMONAD_DIR && $HOME/.local/bin/stack init"
    $sh_c "cd $XMONAD_DIR && $HOME/.local/bin/stack install"
    $sh_c "cd $HOME"
fi

# xmonad installation with cabal yiels v15
#if ! file_exists "$HOME/.cabal/bin/xmonad"; then
#    $sush_c "apt -y install libx11-dev libxft-dev libxinerama-dev libxrandr-dev libxss-dev libxss-dev"
#    $sh_c "cabal update"
#    $sh_c "cabal install --package-env=${XMONAD_DIR}xmonad --lib xmonad xmonad-contrib"
#    $sh_c "cabal install --overwrite-policy=always --package-env=${XMONAD_DIR}xmonad xmonad"
#fi

# commented out is installation of xmobar usign stack
#if ! file_exists "$HOME/.local/bin/xmobar"; then
#     $sush_c "apt -y install libghc-alsa-core-dev libxpm-dev"
#    if [ ! -d "${FOREING_TOOL_REPO_DIR}xmobar" ]; then
#        $sh_c "git clone https://github.com/jaor/xmobar.git ${FOREING_TOOL_REPO_DIR}xmobar"
#    else
#        $sh_c "git -C $NERD_FONTS_DIR pull"
#    fi
#    #TODO: checkout a label
#    $sh_c "git -C ${FOREING_TOOL_REPO_DIR}xmobar checkout b8bcc61a632f49533ff476b3483cb7299866d5dc"
#    $sh_c "cd ${FOREING_TOOL_REPO_DIR}xmobar && stack install --flag xmobar:all_extensions"
#    $sh_c "cd $HOME"
#fi

if ! file_exists "/usr/share/xsessions/xmonad.desktop"; then
    sush_c "cat >/usr/share/xsessions/xmonad.desktop <<-EOF
    [Desktop Entry]
    Encoding=UTF-8
    Name=XMonad
    Comment=Lightweight tiling window manager
    Exec=xmonad
    Icon=xmonad.png
    Type=XSession
EOF"
fi
$sush_c "ln -sf $HOME/.local/bin/xmonad /usr/local/bin/xmonad"

